apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # AWS Fluent Bit daemonset + RBAC + service account, etc.
  - https://raw.githubusercontent.com/aws-samples/amazon-cloudwatch-container-insights/latest/k8s-deployment-manifest-templates/deployment-mode/daemonset/container-insights-monitoring/fluent-bit/fluent-bit.yaml

  # Cluster-info ConfigMap for Fluent Bit
  - fluent-bit-cluster-info-cm.yaml
