apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://aws.github.io/eks-charts
      chart: aws-load-balancer-controller
      targetRevision: 1.17.1
      helm:
        valueFiles:
          - $values/kubernetes/argocd/values/addons-values.yaml
    - repoURL: https://github.com/joshmears169/eks-project-test.git
      targetRevision: section-1a-tf-and-k8s-argocd
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
