autoDiscovery:
  clusterName: orders-platform-test-eks

awsRegion: eu-west-2

replicaCount: 2

rbac:
  serviceAccount:
    create: false
    name: cluster-autoscaler

extraArgs:
  balance-similar-node-groups: "true"
  skip-nodes-with-system-pods: "false"
  skip-nodes-with-local-storage: "false"
  expander: "least-waste"

nodeSelector:
  kubernetes.io/os: linux
